package main

import (
	"flag"
	"log"
	"os"
	"os/exec"
	"strings"
)

func main() {
	output := flag.String("o", "", "output filename (required)")
	pycfg := flag.String("pycfg", "", "python3-config executable name/path")
	flag.Parse()

	if *output == "" {
		flag.Usage()
		os.Exit(1)
	}

	file := &strings.Builder{}
	file.WriteString("// This file is auto-generated by scripts/flags.go; DO NOT EDIT\n")
	file.WriteString("package python\n\n")

	if *pycfg != "" {
		log.Print("specified python3-config")
		file.WriteString("//#cgo LDFLAGS: ")
		c := exec.Command(*pycfg, "--embed", "--ldflags")
		c.Stdout = file
		c.Run()

		file.WriteString("//#cgo CFLAGS: ")
		c = exec.Command(*pycfg, "--includes")
		c.Stdout = file
		c.Run()
	} else {
		file.WriteString("// #cgo pkg-config: python3-embed\n")
		log.Print("python3-command not specified (using pkg-config)")
	}

	file.WriteString("import \"C\"\n")

	os.WriteFile(*output, []byte(file.String()), 0o644)
}
