name: Build UI (cmd/constitutor)

on:
  workflow_dispatch:
    tags:
      - 'v*'

jobs:
  BuildExecs:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Checkout out source code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0
