name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up LibGL, Mesa & X11 libraries
        run: |
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get install -y libgtk-3-dev libasound2-dev libxxf86vm-dev
          sudo apt-get install -y mingw-w64
          sudo apt-get install -y python3 python3-dev
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Run coverage
        run: |
          make setup
          make cover
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
